# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05ec47694518d3c9c263b32e020cd294b2c04844e5a8081d794e69b7884803671265786b232ffe9f6911921961612ac38ed7d92a22d444135454e09b15db5d3f

test:
  secret_key_base: 592b57d41c97aeb37854bbc5ba2a82548adc9cbfe3f9eea39bd5b3bb08466f232889f9eb40b33135c972ff44902e91139229b137bc148d2f20ca5c024f10989c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
